// <auto-generated />
using System;
using GroundUp.Data.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroundUp.Data.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216225001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GroundUp.core.entities.ErrorFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ErrorJson")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ErrorFeedback");
                });

            modelBuilder.Entity("GroundUp.core.entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "View inventory items",
                            Group = "Inventory",
                            Name = "inventory.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create inventory items",
                            Group = "Inventory",
                            Name = "inventory.create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Update inventory items",
                            Group = "Inventory",
                            Name = "inventory.update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Delete inventory items",
                            Group = "Inventory",
                            Name = "inventory.delete"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Export inventory data",
                            Group = "Inventory",
                            Name = "inventory.export"
                        },
                        new
                        {
                            Id = 6,
                            Description = "View error logs",
                            Group = "Errors",
                            Name = "errors.view"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Update error logs",
                            Group = "Errors",
                            Name = "errors.update"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Delete error logs",
                            Group = "Errors",
                            Name = "errors.delete"
                        },
                        new
                        {
                            Id = 9,
                            Description = "View roles",
                            Group = "Roles",
                            Name = "roles.view"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Create roles",
                            Group = "Roles",
                            Name = "roles.create"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Update roles",
                            Group = "Roles",
                            Name = "roles.update"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Delete roles",
                            Group = "Roles",
                            Name = "roles.delete"
                        },
                        new
                        {
                            Id = 13,
                            Description = "View role permissions",
                            Group = "Roles",
                            Name = "roles.permissions.view"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Assign permissions to roles",
                            Group = "Roles",
                            Name = "roles.permissions.assign"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Remove permissions from roles",
                            Group = "Roles",
                            Name = "roles.permissions.remove"
                        },
                        new
                        {
                            Id = 16,
                            Description = "View policies",
                            Group = "Policies",
                            Name = "policies.view"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Create policies",
                            Group = "Policies",
                            Name = "policies.create"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Update policies",
                            Group = "Policies",
                            Name = "policies.update"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Delete policies",
                            Group = "Policies",
                            Name = "policies.delete"
                        },
                        new
                        {
                            Id = 20,
                            Description = "View users",
                            Group = "Users",
                            Name = "users.view"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Create users",
                            Group = "Users",
                            Name = "users.create"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Update users",
                            Group = "Users",
                            Name = "users.update"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Delete users",
                            Group = "Users",
                            Name = "users.delete"
                        },
                        new
                        {
                            Id = 24,
                            Description = "View user roles",
                            Group = "Users",
                            Name = "users.roles.view"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Assign roles to users",
                            Group = "Users",
                            Name = "users.roles.assign"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Remove roles from users",
                            Group = "Users",
                            Name = "users.roles.remove"
                        },
                        new
                        {
                            Id = 27,
                            Description = "View user tenants",
                            Group = "Users",
                            Name = "users.tenants.view"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Assign users to tenants",
                            Group = "Users",
                            Name = "users.tenants.assign"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Remove users from tenants",
                            Group = "Users",
                            Name = "users.tenants.remove"
                        });
                });

            modelBuilder.Entity("GroundUp.core.entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("GroundUp.core.entities.PolicyPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PolicyId", "PermissionId")
                        .IsUnique();

                    b.ToTable("PolicyPermissions");
                });

            modelBuilder.Entity("GroundUp.core.entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("WorkspaceId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name", "RoleType")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GroundUp.core.entities.RolePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleName", "RoleType", "PolicyId")
                        .IsUnique();

                    b.ToTable("RolePolicies");
                });

            modelBuilder.Entity("GroundUp.core.entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Onboarding")
                        .HasColumnType("int");

                    b.Property<int?>("ParentTenantId")
                        .HasColumnType("int");

                    b.Property<string>("Plan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SsoAutoJoinDomainsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("SsoAutoJoinDomains");

                    b.Property<int?>("SsoAutoJoinRoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentTenantId");

                    b.HasIndex("SsoAutoJoinRoleId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("GroundUp.core.entities.TenantInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantInvitations");
                });

            modelBuilder.Entity("GroundUp.core.entities.TenantJoinLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DefaultRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JoinToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantJoinLinks");
                });

            modelBuilder.Entity("GroundUp.core.entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroundUp.core.entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("GroundUp.core.entities.UserTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalUserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserTenants");
                });

            modelBuilder.Entity("GroundUp.core.entities.PolicyPermission", b =>
                {
                    b.HasOne("GroundUp.core.entities.Permission", "Permission")
                        .WithMany("PolicyPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroundUp.core.entities.Policy", "Policy")
                        .WithMany("PolicyPermissions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("GroundUp.core.entities.RolePolicy", b =>
                {
                    b.HasOne("GroundUp.core.entities.Policy", "Policy")
                        .WithMany("RolePolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("GroundUp.core.entities.Tenant", b =>
                {
                    b.HasOne("GroundUp.core.entities.Tenant", "ParentTenant")
                        .WithMany("ChildTenants")
                        .HasForeignKey("ParentTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GroundUp.core.entities.Role", "SsoAutoJoinRole")
                        .WithMany()
                        .HasForeignKey("SsoAutoJoinRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentTenant");

                    b.Navigation("SsoAutoJoinRole");
                });

            modelBuilder.Entity("GroundUp.core.entities.TenantInvitation", b =>
                {
                    b.HasOne("GroundUp.core.entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId");

                    b.HasOne("GroundUp.core.entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("GroundUp.core.entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GroundUp.core.entities.TenantJoinLink", b =>
                {
                    b.HasOne("GroundUp.core.entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("GroundUp.core.entities.UserRole", b =>
                {
                    b.HasOne("GroundUp.core.entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroundUp.core.entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GroundUp.core.entities.UserTenant", b =>
                {
                    b.HasOne("GroundUp.core.entities.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroundUp.core.entities.User", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroundUp.core.entities.Permission", b =>
                {
                    b.Navigation("PolicyPermissions");
                });

            modelBuilder.Entity("GroundUp.core.entities.Policy", b =>
                {
                    b.Navigation("PolicyPermissions");

                    b.Navigation("RolePolicies");
                });

            modelBuilder.Entity("GroundUp.core.entities.Tenant", b =>
                {
                    b.Navigation("ChildTenants");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("GroundUp.core.entities.User", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
